### ISSUE TITLE
Published view doesn't get picked up

### ISSUE THREAD

**Issue by jasperjorna** [doublethreedigital/cookie-notice#19]
### Description
I published the view and made some changes, but the addon doesn't seem to pick up the published view. I've tried to clear all caching as well.

### Steps to reproduce

1. Publish the view: `php artisan vendor:publish --tag=cookie-notice-views`
2. Change some content in the published view

### Additional information

* Statamic version: 3.0.1
* PHP version: 7.4.9

**Comment by damcclean** [comment]
That's weird. I'll have a look now.

**Comment by damcclean** [comment]
Fixed in v3.0.3!

**Comment by damcclean** [comment]
A quick follow up - when you upgrade, make sure to re-run the vendor publish command for the views as they are now published in a different path.
