### ISSUE TITLE
Typo in script notice.blade.php - 'ideConsentFormButton' 

### ISSUE THREAD

**Issue by SophieNikki** [doublethreedigital/cookie-notice#20]
I found an typo in the script part of the notice.blade.php file. At line 56 there is 'ideConsentFormButton' instead of 'hideConsentFormButton'.

    `if (hideConsentFormButton) ideConsentFormButton.addEventListener('click', hideConsentNotice)`

When you hide the cookie modal, and click on the 'manage cookies' button it doesn't come back because of the typo. Is there a way I can fix this typo and push it to my dev and master environments? Because this is in my vendor files it overrides by every composer install. 

Thanks in advance!

**Comment by damcclean** [comment]
Thanks for the issue. 

Would you mind creating a pull request to fix this typo and I'll merge & tag it straight away?

**Comment by SophieNikki** [comment]
I made a commit for the issue. It is my first time doing this so I hope I did it right :). 

I've got another question. In the same file, notice.blade.php, at the bottom of the file the stylesheet is imported. But this stylesheet with tailwind is overriding a lot of my bootstrap styling at my website. Is there a possibility to remove or override the tailwind that is rendered in the plugin? Or get it only used on the cookie consent and not globally on the whole site?

**Comment by damcclean** [comment]
Thanks! I can see the commit, although you still need to [create the pull request](https://github.com/doublethreedigital/cookie-notice/compare) before I can merge it.

Hmm, I thought I prevented that when I built this addon, would you mind opening a separate issue for the Tailwind styles conflicting?

**Comment by SophieNikki** [comment]
I created a pull request but I see there are some errors in the pipeline I guess? I can't see how I can fix this, am I doing something wrong?

https://github.com/doublethreedigital/cookie-notice/pull/21

**Comment by SophieNikki** [comment]
And I opened a new request for the tailwind overriding issue. https://github.com/doublethreedigital/cookie-notice/issues/22

Thanks for your quick replies, really helpful!

**Comment by damcclean** [comment]
Released your fix in [v3.0.4](https://github.com/doublethreedigital/cookie-notice/releases/tag/v3.0.4).

Looks like the testing workflow is broken somehow but that's another issue. Thanks for your help!
