### ISSUE TITLE
Making it possible to un-consent

### ISSUE THREAD

**Issue by danijelk** [doublethreedigital/cookie-notice#25]
We use the plugin to accept 'goole tag manager' as a 'statistics' group, so when one allows it we load the gtag script which adds 5-6 cookies. 

But if a user were to then remove the checkbox from the consent wouldn't it be a great idea from a privacy perspective to get rid of all gtag cookies?

**Comment by damcclean** [comment]
That would be a good idea. What do you think would be the best way of implementing that? 

I don't think Cookie Notice can guess what cookies were created in each statistics group 😄

**Comment by danijelk** [comment]
I would suggest checking if consent changed then simply clear all cookies on site. As you said we have no idea what the names are of gtag manager or any other service.

https://stackoverflow.com/questions/2310558/how-to-delete-all-cookies-of-my-website-in-php

**Comment by damcclean** [comment]
Okay, I'd have to have a bit of a look into this. Not sure if PHP has access to third party cookies or not. If not, we can look at doing it in JavaScript.

Thanks for the issue though, I'll add this issue to my `To Do` list.

**Comment by damcclean** [comment]
Hey! Just had some time to look into this issue properly. 

Looks like the only cookies that PHP can access are the ones for the current site, not third party cookies, like the ones created by Google Analytics or any other service.

It's to do with security - for example, you wouldn't want any website to access cookies for your bank's site, there's a [StackOverflow thread over here](https://stackoverflow.com/questions/17663749/is-it-possible-to-read-3rd-party-cookies).

This probably means that it's not something we can implement, unfortunately.
