### ISSUE TITLE
Better solution around static caching

### ISSUE THREAD

**Issue by duncanmcclean** [doublethreedigital/cookie-notice#40]
Currently, it's difficult to use the Cookie Notice alongside Statamic's static caching feature. There's a couple issues that come up:

* You need a CSRF token to submit the cookie consent form
* If you're using static caching, the state of the popup won't change after submission (at least I *think* that happens)

I need to figure out a solution around these problems.

**Comment by edalzell** [comment]
I would switch this to using all AJAX via Alpine, then it works in all situations.

**Comment by duncanmcclean** [comment]
> I would switch this to using all AJAX via Alpine, then it works in all situations.

That sounds like a good idea. Although, would that conflict if the site itself was using Alpine/using a different version of Alpine?

**Comment by duncanmcclean** [comment]
Fixed in #43
